### ISSUE TITLE
Issue with genesis file creation on qgt-0.1.12

### ISSUE THREAD

**Issue by fox0430** [Consensys/quorum-kubernetes#196] opened 2023-05-26 14:26 UTC
I tried the helm chart for Besu using the latest version.  And, I send TXs, I always get an error `Gas price below configured minimum gas price` even though I set the gas to free.
After doing a little research, it seems that this error occurs when set up using `gqt-0.2.6`.
In `gqt-0.2.3` I was able to successfully send transactions using the same code.

Do I need any additional settings?

Thank you.

**Comment by joshuafernandes** [comment] 2023-06-29 00:00
Hello @fox0430 thanks for this, see https://github.com/Consensys/quorum-dev-quickstart/issues/257 I'll cut a fresh release of the qgt and update here. The issue is to do with the london block and an 0 gas networks, it needs an extra param added to get it working

**Comment by joshuafernandes** [comment] 2023-06-29 00:37
I've just updated the code and pushed out a new qgt image. Can you try that please @fox0430 ?

Cheers

**Comment by fox0430** [comment] 2023-06-29 13:14
@joshuafernandes 

Thank you for your response.

I tried the [latest version](https://github.com/Consensys/quorum-kubernetes/commit/424952ab650d7a1598c1256617104431f97ce288)  and `qgt-0.1.12`. But I cannot start Besu because configmap "besu-genesis" not found.

It seems that another problem has occurred due to the latest version.

```
$ helm install bootnode-1 ./charts/besu-node --namespace quorum --values ./values/bootnode.yml 
$ helm install bootnode-1 ./charts/besu-node --namespace quorum --values ./values/bootnode.yml

$ kubectl get po

NAME                      READY   STATUS      RESTARTS   AGE
besu-genesis-init-6w7ks   0/1     Completed   0          11m
besu-node-bootnode-1-0    0/1     Init:0/1    0          7m53s
```

```
$ kubectl describe po besu-node-bootnode-1-0

Name:             besu-node-bootnode-1-0
Namespace:        quorum
Priority:         0
Service Account:  besu-node-bootnode-1-sa
Node:             minikube/192.168.49.2
Start Time:       Thu, 29 Jun 2023 22:05:41 +0900
Labels:           app.kubernetes.io/component=besu
                  app.kubernetes.io/managed-by=helm
                  app.kubernetes.io/name=besu-statefulset
                  app.kubernetes.io/namespace=quorum
                  app.kubernetes.io/part-of=besu-node-bootnode-1
                  app.kubernetes.io/release=bootnode-1
                  controller-revision-hash=besu-node-bootnode-1-d4bcfb49c
                  statefulset.kubernetes.io/pod-name=besu-node-bootnode-1-0
Annotations:      prometheus.io/path: /metrics
                  prometheus.io/port: 9545
                  prometheus.io/scrape: true
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    StatefulSet/besu-node-bootnode-1
Init Containers:
  volume-permission-besu:
    Container ID:  
    Image:         busybox
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      chown -R 1000:1000 /data
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fvt9b (ro)
Containers:
  bootnode-1-besu:
    Container ID:  
    Image:         hyperledger/besu:22.7.2
    Image ID:      
    Ports:         8545/TCP, 8546/TCP, 8547/TCP, 30303/TCP, 30303/UDP, 9545/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP, 0/TCP
    Command:
      /bin/sh
      -c
    Args:
      exec
      /opt/besu/bin/besu \
        --config-file=/etc/besu/config.toml \
        --Xdns-enabled=true --Xdns-update-enabled=true --Xnat-kube-service-name=besu-node-bootnode-1 \
        --min-gas-price=0 
      
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2G
    Requests:
      cpu:     500m
      memory:  1G
    Liveness:  http-get http://:8545/liveness delay=180s timeout=1s period=60s #success=1 #failure=3
    Environment:
      POD_IP:           (v1:status.podIP)
      POD_NAME:        besu-node-bootnode-1-0 (v1:metadata.name)
      BESU_BOOTNODES:  <set to the key 'bootnodes-string' of config map 'besu-bootnodes'>  Optional: false
    Mounts:
      /config/static from static-nodes (rw)
      /data/besu from data (rw)
      /etc/besu from besu-config (ro)
      /etc/genesis from genesis (ro)
      /keys from besu-keys (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fvt9b (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-besu-node-bootnode-1-0
    ReadOnly:   false
  genesis:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      besu-genesis
    Optional:  false
  static-nodes:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      besu-peers
    Optional:  false
  besu-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      besu-node-bootnode-1-besu-config
    Optional:  false
  besu-keys:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  besu-node-bootnode-1-keys
    Optional:    false
  kube-api-access-fvt9b:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  9m30s                 default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
  Normal   Scheduled         9m28s                 default-scheduler  Successfully assigned quorum/besu-node-bootnode-1-0 to minikube
  Warning  FailedMount       7m25s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[genesis], unattached volumes=[besu-config data kube-api-access-fvt9b besu-keys genesis static-nodes]: timed out waiting for the condition
  Warning  FailedMount       5m8s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[genesis], unattached volumes=[besu-keys genesis static-nodes besu-config data kube-api-access-fvt9b]: timed out waiting for the condition
  Warning  FailedMount       74s (x12 over 9m28s)  kubelet            MountVolume.SetUp failed for volume "genesis" : configmap "besu-genesis" not found
  Warning  FailedMount       35s (x2 over 2m50s)   kubelet            Unable to attach or mount volumes: unmounted volumes=[genesis], unattached volumes=[genesis static-nodes besu-config data kube-api-access-fvt9b besu-keys]: timed out waiting for the condition

```

**Comment by joshuafernandes** [comment] 2023-06-29 21:51
Hello @fox0430 
Can you put logs here for the genesis container please? `besu-genesis-init-6w7ks   0/1     Completed   0          11m` seems to have finished without error so should have created some assets. Is this on a fresh minikube/cluster? 
Cheers

**Comment by fox0430** [comment] 2023-06-29 22:17
@joshuafernandes 

I tried it on a fresh minikube. and I tried it again.
It seems that `besu-genesis-init` is prematurely terminated...

```
$ minikube start --cpus=8 --memory=16000M

$ helm install genesis ./charts/besu-genesis --namespace quorum --create-namespace --values ./values/genesis-besu.yml
```

```
$ kubectl get po 

NAME                      READY   STATUS      RESTARTS   AGE
besu-genesis-init-55j7j   0/1     Completed   0          103s

$ kubectl get cm

NAME               DATA   AGE
besu-bootnodes     1      3m29s
besu-peers         1      3m29s
kube-root-ca.crt   1      3m42s

$ kubectl get secret

NAME                            TYPE                 DATA   AGE
sh.helm.release.v1.genesis.v1   helm.sh/release.v1   1      4m33s
```
```
$ kubectl logs besu-genesis-init-55j7j

Creating config ...
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/quorum-genesis-tool/build/templates/README.md'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at Object.setupOutputFolder (/usr/lib/node_modules/quorum-genesis-tool/build/lib/fileHandler.js:43:38)
    at /usr/lib/node_modules/quorum-genesis-tool/build/lib/networkGenerate.js:60:21
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/quorum-genesis-tool/build/lib/networkGenerate.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/quorum-genesis-tool/build/lib/networkGenerate.js:23:12)
    at generateNetworkConfig (/usr/lib/node_modules/quorum-genesis-tool/build/lib/networkGenerate.js:53:12)
    at /usr/lib/node_modules/quorum-genesis-tool/build/index.js:201:59 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/lib/node_modules/quorum-genesis-tool/build/templates/README.md'
}

Node.js v18.16.1
Creating bootnodes configmap in k8s ...
configmap/besu-bootnodes created

Creating genesis configmap in k8s ...
Error from server (NotFound): configmaps "besu-genesis" not found
error: error reading /besu/genesis.json: no such file or directory
Creating validator secrets in k8s ...
Error from server (NotFound): configmaps "besu-peers" not found
configmap/besu-peers created
Completed ...
```

**Comment by joshuafernandes** [comment] 2023-06-30 01:05
Hello @fox0430 

Apologies for that, had a typo and the qgt version that was installed was 0.2.11. I've now fixed that and pushed a fresh container which should work for you - on the minikube cluster you may need to ssh in and remove the old docker image so you can pull the new one with the same tag. This works fine though:

![image](https://github.com/Consensys/quorum-kubernetes/assets/3722503/82f5d468-f6b2-4582-b8e0-955559b10391)

**Closed by joshuafernandes** 2023-06-30 01:05 UTC

**Comment by fox0430** [comment] 2023-06-30 21:19
@joshuafernandes 

It works fine 0.2.11 now. Thank you.
