### ISSUE TITLE
RPC call to pods from dev helm charts is not working

### ISSUE THREAD

**Issue by victoryeo** [ConsenSys/quorum-kubernetes#126] opened 2022-04-13 01:56 UTC
I deploy besu blockchain using dev helm charts to AWS EKS cluster. After charts are deployed, the rpc call always returns 404 not found.
 
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://<ingress_ip>/rpc  
```<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.21.6</center>  
</body>  
</html> 
```  
Here is the deployment from dev helm chart.
```
$ kubectl get svc -n quorum
NAME                         TYPE           CLUSTER-IP       EXTERNAL-IP                                                              PORT(S)                                                                              AGE
besu-ingress-nginx-ingress   LoadBalancer   172.20.183.89    <ingress_ip>   80:30286/TCP,443:31335/TCP                                                           17h
besu-node-bootnode-1         ClusterIP      172.20.109.226   <none>                                                                   8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP                              17h
besu-node-bootnode-2         ClusterIP      172.20.193.48    <none>                                                                   8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP                              17h
besu-node-member-1           ClusterIP      172.20.193.177   <none>                                                                   8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP,9000/TCP,9080/TCP,9101/TCP   17h
besu-node-validator-1        ClusterIP      172.20.49.153    <none>                                                                   8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP                              17h
besu-node-validator-2        ClusterIP      172.20.188.185   <none>                                                                   8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP                              17h
besu-node-validator-3        ClusterIP      172.20.226.92    <none>                                                                   8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP                              17h
besu-node-validator-4        ClusterIP      172.20.189.0     <none>                                                                   8545/TCP,8546/TCP,8547/TCP,30303/TCP,30303/UDP,9545/TCP                              17h
```
What could go wrong? Why port 8545 is not open on ingress?

**Comment by victoryeo** [comment] 2022-04-15 05:16
I create PR to address the issue.
https://github.com/ConsenSys/quorum-kubernetes/pull/129

**Comment by joshuafernandes** [comment] 2022-04-19 10:43
Hello @victoryeo thanks for this, but not quite able to figure out how a volume fixes an ingress route. Could you give me a list of what steps you did please so I can reproduce this issue you are seeing

**Comment by victoryeo** [comment] 2022-04-25 00:34
Probably Persistent Volume is unrelated to ingress route. By the way, is PV required for AWS EKS cluster ?

**Comment by joshuafernandes** [comment] 2022-04-27 01:42
Hello @victoryeo We're unable to reproduce this issue. But we've done a merge of dev and prod to make it easier to use. Could you try it out after #133 is merged and let us know if you have any issues?

PV isn't required but recommended. We use seperate data volumes to store the blockchain data, over the default of the host nodes. This is similar to using separate volumes to store data when using docker containers natively or via docker-compose. This is done for a couple of reasons; firstly, containers are mortal and we don't want to store data on them, secondly, host nodes can fail and we would like the chain data to persist.  

Cheers

**Closed by joshuafernandes** 2022-04-27 01:42 UTC
